/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int APARENTESES = 6;
  /** RegularExpression Id. */
  int FPARENTESES = 7;
  /** RegularExpression Id. */
  int ACHAVES = 8;
  /** RegularExpression Id. */
  int FCHAVES = 9;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 10;
  /** RegularExpression Id. */
  int ATTR = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int FUNCTION = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int SOMA = 19;
  /** RegularExpression Id. */
  int SUB = 20;
  /** RegularExpression Id. */
  int MULT = 21;
  /** RegularExpression Id. */
  int DIV = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int MENORQ = 25;
  /** RegularExpression Id. */
  int MAIORQ = 26;
  /** RegularExpression Id. */
  int EQUAL = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int VIRGULA = 30;
  /** RegularExpression Id. */
  int NUM = 31;
  /** RegularExpression Id. */
  int ID = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"void\"",
    "\"float\"",
    "\"boolean\"",
    "\"return\"",
    "\"while\"",
    "\"fun\"",
    "\"if\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "<NUM>",
    "<ID>",
  };

}
