/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int APAR = 9;
  /** RegularExpression Id. */
  int FPAR = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int PV = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int ATRIB = 14;
  /** RegularExpression Id. */
  int PRINT = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int BOOL = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int MULT = 22;
  /** RegularExpression Id. */
  int DIV = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int COMP = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int LESSER = 28;
  /** RegularExpression Id. */
  int BIGGER = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int THEN = 31;
  /** RegularExpression Id. */
  int FUN = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int READ = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"(\"",
    "\")\"",
    "\"newVar\"",
    "\";\"",
    "\"float\"",
    "\"=\"",
    "\"printOut\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"boolean\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"true\"",
    "\"false\"",
    "\"==\"",
    "\"|\"",
    "\"<\"",
    "\">\"",
    "\"&\"",
    "\"then\"",
    "\"fun\"",
    "\",\"",
    "\"readInput\"",
    "<NUM>",
    "<ID>",
  };

}
